language: c

notifications:
  email: false

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux

before_script:
  - echo ${LANG}
  - echo ${LC_ALL}
  - sudo apt-get update -qq; sudo apt-get install -y libjson0-dev;

script:
  - chmod +x ./autogen.sh ./get-version
  - ./autogen.sh
  - ./configure --prefix=/tmp/
  - make
  - make install
