language: c

notifications:
  email: false

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_script:
  - echo ${LANG}
  - echo ${LC_ALL}
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y libjson0-dev; fi

script:
  - make CC=${CC} LD=${CC} OPTIM=NONE test
  - ./tests/main.out -t ${PB_TOKEN_KEY}
