language: c

notifications:
  email: false

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux

before_script:
  - echo ${LANG}
  - echo ${LC_ALL}
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y libcurl4-openssl-dev libjson-glib-dev libmagic-dev; fi

script:
  - ./autogen.sh --enable-debug
  - make
