language: c

notifications:
  email: false

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux

before_script:
  - echo ${LANG}
  - echo ${LC_ALL}
  - sudo apt-get update -qq
  - sudo apt-get install -y libcurl4-openssl-dev libjson-glib-dev libmagic-dev

script:
  - ./autogen.sh --enable-debug
  - make check
